import type { ShellState } from "./shellTypes";

/** Sparse Phase 4 initial state — storyboard beat 1. */
export function createInitialShellState(): ShellState {
  return {
    room: "global",
    selectedParticipantId: "p1",
    followActive: false,
    followLocked: false,
    exchangeOpen: false,
    interactionFrozen: false,
    participantTab: "Create",
    createSubMode: "piano",
    transportPlaying: false,
    transportBar: 0,
    transportBeat: 0,
    selectedExchangeClipId: null,
    selectedMixerChannel: 0,
    dockMode: "preview",
    workspaceDraftId: "midi-opening-bass",
    workspaceBleed: "low",
    activeMasterDraftId: null,
    participants: [
      { id: "p1", name: "Alex", color: "#e76f51", taskProfile: "MIDI", active: true, projectedRoom: "participant", projectedTab: "Create" },
      { id: "p2", name: "Jordan", color: "#2a9d8f", taskProfile: "Devices", active: false, projectedRoom: "participant", projectedTab: "Devices" },
      { id: "p3", name: "Sam", color: "#e9c46a", taskProfile: "Mix", active: false, projectedRoom: "mixer", projectedTab: "Mix" },
    ],
    exchangeClips: [],
    arrangementTracks: [
      { id: "t-drums", name: "Drums", identity: "Kick · Alex" },
      { id: "t-bass", name: "Bass", identity: "Sub · Alex" },
      { id: "t-lead", name: "Lead", identity: "Hook · Jordan" },
      { id: "t-fx", name: "FX", identity: "Send · Sam" },
    ],
    timelineClips: [],
    arrangementSlots: [
      { id: "s1", clipId: null, state: "empty", label: "Master slot A" },
      { id: "s2", clipId: null, state: "empty", label: "Master slot B" },
      { id: "s3", clipId: null, state: "empty", label: "Master slot C" },
    ],
    dockSlots: [
      { index: 0, label: "Drop parameter", type: "knob", value: 0, badge: null, sourceTrack: null, sourceClip: null, sourceParam: null, mapped: false },
      { index: 1, label: "Drop parameter", type: "knob", value: 0, badge: null, sourceTrack: null, sourceClip: null, sourceParam: null, mapped: false },
      { index: 2, label: "Drop parameter", type: "fader", value: 0, badge: null, sourceTrack: null, sourceClip: null, sourceParam: null, mapped: false },
      { index: 3, label: "Drop parameter", type: "fader", value: 0, badge: null, sourceTrack: null, sourceClip: null, sourceParam: null, mapped: false },
      { index: 4, label: "Mute", type: "toggle", value: 0, badge: null, sourceTrack: null, sourceClip: null, sourceParam: null, mapped: false },
      { index: 5, label: "FX Hit", type: "momentary", value: 0, badge: null, sourceTrack: null, sourceClip: null, sourceParam: null, mapped: false },
      { index: 6, label: "Drop parameter", type: "knob", value: 0, badge: null, sourceTrack: null, sourceClip: null, sourceParam: null, mapped: false },
      { index: 7, label: "Drop parameter", type: "knob", value: 0, badge: null, sourceTrack: null, sourceClip: null, sourceParam: null, mapped: false },
    ],
    activityFeed: ["Session ready · Shiki no Uta public pack"],
  };
}

/** Fixture-rich state for shell regression tests (visual hierarchy preserved). */
export function createFixtureShellState(): ShellState {
  return {
    ...createInitialShellState(),
    transportBar: 5,
    transportBeat: 2,
    selectedExchangeClipId: "c4",
    exchangeClips: [
      {
        id: "c1",
        title: "pulse-r1",
        revision: 1,
        creatorId: "p1",
        contributorId: null,
        lifecycle: "Available",
        thumbnail: "wave",
        lineageParentId: null,
        forkOf: null,
        draftId: "midi-opening-bass",
      },
      {
        id: "c2",
        title: "melody-draft",
        revision: 2,
        creatorId: "p2",
        contributorId: "p2",
        lifecycle: "In Progress",
        thumbnail: "notes",
        lineageParentId: null,
        forkOf: null,
        draftId: "midi-opening-guitar",
      },
      {
        id: "c3",
        title: "shiki-hook",
        revision: 1,
        creatorId: "p3",
        contributorId: "p3",
        lifecycle: "Review",
        thumbnail: "steps",
        lineageParentId: null,
        forkOf: "c1",
        draftId: "midi-opening-bass-fork",
      },
      {
        id: "c4",
        title: "bass-loop",
        revision: 3,
        creatorId: "p1",
        contributorId: "p1",
        lifecycle: "Ready",
        thumbnail: "wave",
        lineageParentId: null,
        forkOf: null,
        draftId: "midi-opening-bass",
      },
    ],
    timelineClips: [
      { id: "tc1", exchangeClipId: "c1", trackId: "t-drums", startBar: 1, lengthBars: 4, variant: "normal" },
      { id: "tc2", exchangeClipId: "c4", trackId: "t-bass", startBar: 3, lengthBars: 8, variant: "active" },
      { id: "tc3", exchangeClipId: "c2", trackId: "t-lead", startBar: 5, lengthBars: 4, variant: "selected" },
      { id: "tc4", exchangeClipId: "c3", trackId: "t-fx", startBar: 9, lengthBars: 2, variant: "staged" },
    ],
    arrangementSlots: [
      { id: "s1", clipId: null, state: "empty", label: "Master slot A" },
      { id: "s2", clipId: "c3", state: "staged", label: "shiki-hook" },
      { id: "s3", clipId: "c4", state: "active", label: "bass-loop" },
    ],
    dockSlots: [
      { index: 0, label: "Cutoff", type: "knob", value: 0.42, badge: null, sourceTrack: "Bass", sourceClip: "bass-loop", sourceParam: "Filter · Cutoff", mapped: true },
      { index: 1, label: "Wet", type: "knob", value: 0.28, badge: null, sourceTrack: "FX", sourceClip: "shiki-hook", sourceParam: "Delay · Wet", mapped: true },
      { index: 2, label: "Level", type: "fader", value: 0.72, badge: null, sourceTrack: "Drums", sourceClip: "pulse-r1", sourceParam: "Channel · Level", mapped: true },
      { index: 3, label: "Send", type: "fader", value: 0.35, badge: null, sourceTrack: "Lead", sourceClip: "melody-draft", sourceParam: "Reverb · Send", mapped: true },
      { index: 4, label: "Mute", type: "toggle", value: 0, badge: null, sourceTrack: null, sourceClip: null, sourceParam: null, mapped: false },
      { index: 5, label: "FX Hit", type: "momentary", value: 0, badge: null, sourceTrack: null, sourceClip: null, sourceParam: null, mapped: false },
      { index: 6, label: "Drop parameter", type: "knob", value: 0, badge: null, sourceTrack: null, sourceClip: null, sourceParam: null, mapped: false },
      { index: 7, label: "Drop parameter", type: "knob", value: 0, badge: null, sourceTrack: null, sourceClip: null, sourceParam: null, mapped: false },
    ],
    activityFeed: ["bass-loop active on Shared Master · bar 5"],
  };
}
